resourceNames:
  - name: table
    wave: 2
    env: svil
    image: docker.io/fdaluisio/flinkjob:v1
    imagepullpolicy: Always
    sql_runner_args_values: /opt/flink/usrlib/sql-scripts/table.sql
    storageclassname: crc-csi-hostpath-provisioner
    storage: 100M
    kafkaUser: fd-kafkauser
    cluster_ca_cert: svil-es-kafka-cluster-ca-cert
    clients_ca_cert: svil-es-kafka-clients-ca-cert
    needsStorage: false
    storageclassname: crc-csi-hostpath-provisioner
    storage: 1Gi
    ibmlicense: EventAutomationProduction
    namespace: event-automation
    jobmanager:
      memory: 1024m
      cpu: 0.5
    taskmanager:
      memory: 2048m
      cpu: 1
