resourceNames:
  - name: postgres
    wave: 3
    env: svil
    image: docker.io/fdaluisio/flinkjob:v1
    imagepullpolicy: Always
    sql_runner_args_values: /opt/flink/usrlib/sql-scripts/postgres.sql
    storageclassname: crc-csi-hostpath-provisioner
    storage: 100M
    kafkaUser: fd-kafkauser
    cluster_ca_cert: svil-es-kafka-cluster-ca-cert
    cluster_ca_cert_key: ca.crt
    brokers_cert: svil-es-kafka-kafka-brokers
    brokers_cert_key: svil-es-kafka-kafka-0.crt
    needsStorage: false
    storageclassname: crc-csi-hostpath-provisioner
    storage: 1Gi
    ibmlicense: EventAutomationProduction
    namespace: event-automation
    jobmanager:
      memory: 1024m
      cpu: 0.5
    taskmanager:
      memory: 2048m
      cpu: 1
