{{- range .Values.resourceNames }}
---
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: {{ .env }}-fd-{{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .wave | quote }}
spec:
  image: {{ .image }} 
  imagePullPolicy: {{ .imagepullpolicy }}
  flinkVersion: "v1_18"
  flinkConfiguration:
    license.use: EventAutomationNonProduction
    license.license: L-HRZF-DWHH7A
    license.accept: 'true'
    high-availability.type: org.apache.flink.kubernetes.highavailability.KubernetesHaServicesFactory
    high-availability.storageDir: 'file:///opt/flink/volume/flink-ha'
    restart-strategy: failure-rate
    restart-strategy.failure-rate.max-failures-per-interval: '10'
    restart-strategy.failure-rate.failure-rate-interval: 10 min
    restart-strategy.failure-rate.delay: 30 s
    execution.checkpointing.interval: '5000'
    execution.checkpointing.unaligned: 'false'
    state.backend.type: rocksdb
    state.backend.incremental: 'true'
    state.backend.rocksdb.use-bloom-filter: 'true'
    state.checkpoints.dir: 'file:///opt/flink/volume/flink-cp'
    state.checkpoints.num-retained: '3'
    state.savepoints.dir: 'file:///opt/flink/volume/flink-sp'
    taskmanager.numberOfTaskSlots: '10'
    table.exec.source.idle-timeout: 30 s
    security.ssl.enabled: 'false'  
  serviceAccount: flink
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-template
    spec:
      containers:
        - name: flink-main-container
          volumeMounts:
            - name: flink-logs
              mountPath: /opt/flink/log
            - name: flink-volume
              mountPath: /opt/flink/volume
            - name: cert-cluster-ca-cert
              mountPath: /opt/flink/certs/
              readOnly: true
#            - name: cert-clients-ca-cert
#              mountPath: /opt/flink/certs/
#              readOnly: true
          env:
            - name: SQL_RUNNER_ARGS
              value: {{ .sql_runner_args_values | quote }}
            - name: KUSER_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: {{ .kafkaUser }}
                  key: sasl.jaas.config
            - name: CLUSTER_CA_CERT
              valueFrom:
                secretKeyRef:
                  name: {{ .cluster_ca_cert }}
                  key: ca.crt
            - name: CLIENTS_CA_CERT
              valueFrom:
                secretKeyRef:
                  name: {{ .clients_ca_cert }}
                  key: ca.crt
      volumes:
        - name: flink-logs
          emptyDir: {}
        - name: flink-volume
          persistentVolumeClaim:
            claimName: flink-pvc-{{ .name }}
  jobManager:
    replicas: 1
    resource:
      memory: 1024m
      cpu: 0.5
  taskManager:
    resource:
      memory: 2048m
      cpu: 1
  job:
    jarURI: local:///opt/flink/usrlib/sql-runner.jar
    args: [ {{ .sql_runner_args_values | quote }} ]
    parallelism: 1
    state: running
    upgradeMode: savepoint
  mode: native

{{- end }}
