{{- range .Values.resourceNames }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: flink-pvc-{{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .wave | quote }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .storage }}
  storageClassName: {{ .storageclassname }}
{{- end }}
