
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: svil-fd
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
        - valuesHelmFile: values_01.yaml
          appName: fd-table
        #- valuesHelmFile: values_02.yaml
        #   appName: fd-postgres
  template:
    metadata: 
      name: '{{appName}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/fdaluisio/eventprocessing.git'
        revision: HEAD
        path: flink-instances/
        helm:
          valueFiles:
            - '{{valuesHelmFile}}'
      destination:
        name: 'in-cluster'
        namespace: myproject
      syncPolicy: {}
